projects:
  ModernFactions:
    path: ModernFactions
    libs:
      - src: Falkirks/spoondetector/spoondetector
        version: ^0.0.1
      - src: poggit/libasynql/libasynql
        version: ^3.1.1
      - src: SOF3/libglocal/libglocal
        version: ^0.4.0
      - src: SOF3/libkinetic/libkinetic
        version: ^0.0.3
